-- ESTADO
insert into estado(est_id, est_sigla, est_nome) values(1, 'AC', 'Acre');
insert into estado(est_id, est_sigla, est_nome) values(2, 'AL', 'Alagoas');
insert into estado(est_id, est_sigla, est_nome) values(3, 'AM', 'Amazonas');
insert into estado(est_id, est_sigla, est_nome) values(4, 'AP', 'Amapá');
insert into estado(est_id, est_sigla, est_nome) values(5, 'BA', 'Bahia');
insert into estado(est_id, est_sigla, est_nome) values(6, 'CE', 'Ceará');
insert into estado(est_id, est_sigla, est_nome) values(7, 'DF', 'Distrito Federal');
insert into estado(est_id, est_sigla, est_nome) values(8, 'ES', 'Espirito Santo');
insert into estado(est_id, est_sigla, est_nome) values(9, 'GO', 'Goiás');
insert into estado(est_id, est_sigla, est_nome) values(10, 'MA', 'Maranhão');
insert into estado(est_id, est_sigla, est_nome) values(11, 'MG', 'Minas Gerais');
insert into estado(est_id, est_sigla, est_nome) values(12, 'MS', 'Mato Grosso do Sul');
insert into estado(est_id, est_sigla, est_nome) values(13, 'MT', 'Mato Grosso');
insert into estado(est_id, est_sigla, est_nome) values(14, 'PA', 'Pará');
insert into estado(est_id, est_sigla, est_nome) values(15, 'PB', 'Paraíba');
insert into estado(est_id, est_sigla, est_nome) values(16, 'PE', 'Pernambuco');
insert into estado(est_id, est_sigla, est_nome) values(17, 'PI', 'Piauí');
insert into estado(est_id, est_sigla, est_nome) values(18, 'PR', 'Paraná');
insert into estado(est_id, est_sigla, est_nome) values(19, 'RJ', 'Rio de Janeiro');
insert into estado(est_id, est_sigla, est_nome) values(20, 'RN', 'Rio Grande do Norte');
insert into estado(est_id, est_sigla, est_nome) values(21, 'RO', 'Rondonia');
insert into estado(est_id, est_sigla, est_nome) values(22, 'RR', 'Roraima');
insert into estado(est_id, est_sigla, est_nome) values(23, 'RS', 'Rio Grande do Sul');
insert into estado(est_id, est_sigla, est_nome) values(24, 'SC', 'Santa Catarina');
insert into estado(est_id, est_sigla, est_nome) values(25, 'SE', 'Sergipe');
insert into estado(est_id, est_sigla, est_nome) values(26, 'SP', 'São Paulo');
insert into estado(est_id, est_sigla, est_nome) values(27, 'TO', 'Tocantins');

insert into cidade(cid_id, est_id, cid_descr) values(1,7,'Brasília');
insert into cidade(cid_id, est_id, cid_descr) values(2,1,'Rodrigues Alves');
insert into cidade(cid_id, est_id, cid_descr) values(3,1,'Santa Rosa do Purus');
insert into cidade(cid_id, est_id, cid_descr) values(4,2,'Água Branca');
insert into cidade(cid_id, est_id, cid_descr) values(5,2,'Anadia');
insert into cidade(cid_id, est_id, cid_descr) values(6,3,'Anamã');
insert into cidade(cid_id, est_id, cid_descr) values(7,3,'Anori');
insert into cidade(cid_id, est_id, cid_descr) values(8,4,'Pracuúba');
insert into cidade(cid_id, est_id, cid_descr) values(9,4,'Santana');
insert into cidade(cid_id, est_id, cid_descr) values(10,5,'Água Fria');
insert into cidade(cid_id, est_id, cid_descr) values(11,5,'Aiquara');
insert into cidade(cid_id, est_id, cid_descr) values(12,6,'Umari');
insert into cidade(cid_id, est_id, cid_descr) values(13,6,'Umirim');
insert into cidade(cid_id, est_id, cid_descr) values(14,8,'Vila Velha');
insert into cidade(cid_id, est_id, cid_descr) values(15,8,'Vitória');
insert into cidade(cid_id, est_id, cid_descr) values(16,9,'Abadia de Goiás');
insert into cidade(cid_id, est_id, cid_descr) values(17,9,'Abadiânia');
insert into cidade(cid_id, est_id, cid_descr) values(18,10,'Aldeias Altas');
insert into cidade(cid_id, est_id, cid_descr) values(19,10,'Altamira do Maranhão');
insert into cidade(cid_id, est_id, cid_descr) values(20,11,'Vieiras');
insert into cidade(cid_id, est_id, cid_descr) values(21,11,'Virgem da Lapa');
insert into cidade(cid_id, est_id, cid_descr) values(22,12,'Antônio João');
insert into cidade(cid_id, est_id, cid_descr) values(23,12,'Aparecida do Taboado');
insert into cidade(cid_id, est_id, cid_descr) values(24,13,'Vila Bela da Santíssima Trindade');
insert into cidade(cid_id, est_id, cid_descr) values(25,13,'Vila Rica');
insert into cidade(cid_id, est_id, cid_descr) values(26,14,'Água Azul do Norte');
insert into cidade(cid_id, est_id, cid_descr) values(27,14,'Alenquer');
insert into cidade(cid_id, est_id, cid_descr) values(28,15,'Vista Serrana');
insert into cidade(cid_id, est_id, cid_descr) values(29,15,'Zabelê');
insert into cidade(cid_id, est_id, cid_descr) values(30,16,'Água Preta');
insert into cidade(cid_id, est_id, cid_descr) values(31,16,'Águas Belas');
insert into cidade(cid_id, est_id, cid_descr) values(32,17,'Vila Nova do Piauí');
insert into cidade(cid_id, est_id, cid_descr) values(33,17,'Wall Ferraz');
insert into cidade(cid_id, est_id, cid_descr) values(34,18,'Altamira do Paraná');
insert into cidade(cid_id, est_id, cid_descr) values(35,18,'Alto Paraíso');
insert into cidade(cid_id, est_id, cid_descr) values(36,19,'Armação dos Búzios');
insert into cidade(cid_id, est_id, cid_descr) values(37,19,'Arraial do Cabo');
insert into cidade(cid_id, est_id, cid_descr) values(38,20,'Viçosa');
insert into cidade(cid_id, est_id, cid_descr) values(39,20,'Vila Flor');
insert into cidade(cid_id, est_id, cid_descr) values(40,21,'Alta Floresta D''Oeste');
insert into cidade(cid_id, est_id, cid_descr) values(41,21,'Alto Alegre dos Parecis');
insert into cidade(cid_id, est_id, cid_descr) values(43,22,'Cantá');
insert into cidade(cid_id, est_id, cid_descr) values(44,22,'Caracaraí');
insert into cidade(cid_id, est_id, cid_descr) values(45,23,'Vista Alegre do Prata');
insert into cidade(cid_id, est_id, cid_descr) values(46,23,'Westfalia');
insert into cidade(cid_id, est_id, cid_descr) values(47,23,'Xangri-lá');
insert into cidade(cid_id, est_id, cid_descr) values(48,24,'Xaxim');
insert into cidade(cid_id, est_id, cid_descr) values(49,24,'Zortéa');
insert into cidade(cid_id, est_id, cid_descr) values(50,25,'Areia Branca');
insert into cidade(cid_id, est_id, cid_descr) values(51,25,'Barra dos Coqueiros');
insert into cidade(cid_id, est_id, cid_descr) values(52,26,'Vista Alegre do Alto');
insert into cidade(cid_id, est_id, cid_descr) values(53,26,'Zacarias');
insert into cidade(cid_id, est_id, cid_descr) values(54,27,'Abreulândia');
insert into cidade(cid_id, est_id, cid_descr) values(55,27,'Aguiarnópolis');